/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx}",
    ],
    theme: {
        extend: {
            colors: {
                background: "#f8f9ff",
                surface: "#f8f9ff",
                "surface-container-low": "#eff4ff",
                "surface-container-lowest": "#ffffff",
                "surface-container": "#e5eeff",
                "surface-container-high": "#dce9ff",
                "surface-container-highest": "#d3e4fe",
                "surface-variant": "#d3e4fe",
                "surface-tint": "#4e5e81",
                "surface-bright": "#f8f9ff",
                "surface-dim": "#cbdbf5",
                
                primary: "#031635",
                "on-primary": "#ffffff",
                "primary-container": "#1a2b4b",
                "on-primary-container": "#8293b8",
                "primary-fixed": "#d8e2ff",
                "primary-fixed-dim": "#b6c6ef",
                "on-primary-fixed": "#081b3a",
                "on-primary-fixed-variant": "#364768",

                secondary: "#a73920",
                "on-secondary": "#ffffff",
                "secondary-container": "#fe795a",
                "on-secondary-container": "#6f1300",
                "secondary-fixed": "#ffdad2",
                "secondary-fixed-dim": "#ffb4a3",
                "on-secondary-fixed": "#3d0600",
                "on-secondary-fixed-variant": "#86220a",

                tertiary: "#231400",
                "on-tertiary": "#ffffff",
                "tertiary-container": "#3e2700",
                "on-tertiary-container": "#b08d5b",
                "tertiary-fixed": "#ffddb1",
                "tertiary-fixed-dim": "#e8c08a",
                "on-tertiary-fixed": "#291800",
                "on-tertiary-fixed-variant": "#5d4217",

                "on-surface": "#0b1c30",
                "on-surface-variant": "#44474e",
                "inverse-surface": "#213145",
                "inverse-on-surface": "#eaf1ff",
                "inverse-primary": "#b6c6ef",
                
                outline: "#75777f",
                "outline-variant": "#c5c6cf",
                
                error: "#ba1a1a",
                "on-error": "#ffffff",
                "error-container": "#ffdad6",
                "on-error-container": "#93000a",
            },
            fontFamily: {
                sans: ["Manrope", "system-ui", "sans-serif"],
                "display-bold": ["Manrope"],
                "body-regular": ["Manrope"],
                "body-medium": ["Manrope"],
                "label-bold": ["Manrope"],
                "caption-regular": ["Manrope"],
                "caption-medium": ["Manrope"],
            },
            borderRadius: {
                DEFAULT: "0.125rem",
                lg: "0.25rem",
                xl: "0.5rem",
                full: "0.75rem",
            },
            spacing: {
                xs: "8px",
                sm: "12px",
                md: "16px",
                lg: "24px",
                xl: "32px",
                base: "4px",
                gutter: "12px",
                "container-margin": "16px",
            }
        },
    },
    plugins: [],
}
